# Generated by Django 5.1.5 on 2025-01-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_webpage_repassword_alter_webpage_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='package',
        ),
    ]
